name: touchins
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.18.1
  cupertino_icons: ^0.1.3
  flare_flutter: any
  provider: ^3.2.0
  shared_preferences: ^0.5.10
  table_calendar: ^2.2.3
  date_format: 1.0.8
  google_maps_flutter: ^0.5.30
  location: ^3.0.2
  geolocator: ^5.1.3

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter
  dots_indicator: ^1.2.0
  mockito: 4.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/blueLogo.png"
  

flutter:

  uses-material-design: true

  fonts:
    - family: PlayfairDisplay     
      fonts:
        - asset: assets/fonts/PlayfairDisplay.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/HomeIcon.flr
    - assets/TickMark.flr
    - assets/Chart.flr
    - assets/Loading.flr
    - assets/blueLogo.svg
    - assets/blueLogo.png

 